# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: QASE CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "10 19 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      QASE_EMAIL: ${{ secrets.QASE_EMAIL }}
      QASE_PASSWORD: ${{ secrets.QASE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Chrome
        uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: chrome
          version: latest

      - name: Run Tests
        run: mvn clean test -Duser="${QASE_EMAIL}" -Dpassword="${QASE_PASSWORD}"

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-branch
          path: gh-branch
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-branch
          PUBLISH_DIR: allure-history