name: Java CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "10 19 * * 5"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean test -DsuiteXmlFile=src/test/resources/xml/CrossBrowserTest.xml

      - name: Install Allure
        run: |
          $url = "https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.zip"
          Invoke-WebRequest -Uri $url -OutFile "allure.zip"
          Expand-Archive -Path "allure.zip" -DestinationPath "allure" -Force

      - name: Generate Allure Report
        run: .\allure\allure-2.24.0\bin\allure.bat generate -c -o allure-report target/allure-results

      - name: Get history
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: history

      - name: Copy history
        run: |
          robocopy history\allure-history allure-report\history /E
          if %ERRORLEVEL% GTR 3 exit 0  # Игнорируем ошибки "файлы не найдены"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          destination_dir: allure-history
          keep_files: true